"""add_payment_method_table

Revision ID: 62f950a37561
Revises:
Create Date: 2026-01-07 09:06:41.494470
"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "62f950a37561"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_methods",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("min_modifier", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("max_modifier", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("points_modifier", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("additional_item_schema", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_payment_methods_id"), "payment_methods", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_methods_id"), table_name="payment_methods")
    op.drop_table("payment_methods")
    # ### end Alembic commands ###
